name = "HealthMLBase"
uuid = "607c11b8-770f-4df0-ace8-6eaa1ea2719e"
authors = ["JuliaHealth contributors"]
version = "0.2.0"

[deps]
HealthBase = "94e1309d-ccf4-42de-905f-515f1d7b1cae"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
HealthBase = "0.1"
MLJModelInterface = "0.3"
Reexport = "0.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
