name = "HealthMLBase"
uuid = "607c11b8-770f-4df0-ace8-6eaa1ea2719e"
authors = ["JuliaHealth contributors"]
version = "0.3.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
